const jwt = require("jsonwebtoken");
const Driver = require("../models/Driver");
const Vehicle = require("../models/Vehicle");
const DriverDocument = require("../models/DriverDocument");
const Audit = require("../models/VerificationAuditLog");
const tokenFor = (driver) => jwt.sign({ id: driver._id, role: driver.role }, process.env.JWT_SECRET || "moventra_super_secure_jwt_secret_key_2026", { expiresIn: "30d" });
const requiredTypes = ["DRIVING_LICENSE", "VEHICLE_RC", "VEHICLE_INSURANCE", "POLLUTION_CERTIFICATE"];
const expired = (date) => date && new Date(date) < new Date();
const audit = (driverId, actorId, action, targetType, targetId, reason) => Audit.create({ driverId, actorId, action, targetType, targetId, reason });

exports.register = async (req, res) => {
  const { name, email, phone, password, confirmPassword, dateOfBirth, address, emergencyContact, vehicle } = req.body;
  if (!name || !email || !phone || !password || !dateOfBirth || !address?.line1 || !address?.city || !address?.state || !address?.pincode || !emergencyContact?.name || !emergencyContact?.phone || !vehicle) return res.status(400).json({ success: false, message: "Complete all personal, address, emergency contact and vehicle details before registering." });
  if (password !== confirmPassword) return res.status(400).json({ success: false, message: "Passwords do not match." });
  if (await Driver.findOne({ $or: [{ email: email.toLowerCase().trim() }, { phone: phone.trim() }] })) return res.status(409).json({ success: false, message: "An account with this email or phone already exists." });
  let driver;
  try {
    driver = await Driver.create({
      name, email, phone, password, dateOfBirth, address,
      emergencyContact, status: "pending", role: "driver",
      verification: { profileCompleted: true, status: "pending" },
    });
    await Vehicle.create({ ...vehicle, driverId: driver._id });
  } catch (error) {
    if (driver) await Driver.deleteOne({ _id: driver._id });
    if (error.code === 11000) {
      const field = error.keyPattern?.registrationNumber ? "registration number" : "email or phone";
      return res.status(409).json({ success: false, message: `An account with this ${field} already exists.` });
    }
    if (error.name === "ValidationError" || error.name === "CastError") return res.status(400).json({ success: false, message: error.message });
    throw error;
  }
  res.status(201).json({ success: true, message: "Driver registration completed.", token: tokenFor(driver), driver });
};
exports.login = async (req, res) => { const driver = await Driver.findOne({ email: req.body.email?.toLowerCase().trim() }).select("+password"); if (!driver || !(await driver.comparePassword(req.body.password || ""))) return res.status(401).json({ success: false, message: "Invalid email or password." }); res.json({ success: true, token: tokenFor(driver), driver }); };
exports.me = async (req, res) => { const [vehicle, documents] = await Promise.all([Vehicle.findOne({ driverId: req.driver._id }), DriverDocument.find({ driverId: req.driver._id })]); res.json({ success: true, driver: req.driver, vehicle, documents }); };
exports.updateAvailability = async (req, res) => {
  const { availability } = req.body;
  if (!["online", "offline"].includes(availability)) return res.status(400).json({ success: false, message: "Availability must be online or offline." });
  if (availability === "online" && (req.driver.status === "suspended" || req.driver.status !== "active" || req.driver.verification.status !== "approved")) {
    return res.status(403).json({ success: false, message: req.driver.status === "suspended" ? "Suspended accounts cannot go online." : "Complete driver verification before going online." });
  }
  req.driver.availability = availability;
  await req.driver.save();
  res.json({ success: true, availability: req.driver.availability });
};
exports.updateProfile = async (req, res) => { const allowed = ["name", "dateOfBirth", "profilePhotoKey", "address", "emergencyContact"]; allowed.forEach((key) => { if (req.body[key] !== undefined) req.driver[key] = req.body[key]; }); req.driver.verification.profileCompleted = Boolean(req.driver.name && req.driver.dateOfBirth && req.driver.address?.line1 && req.driver.address?.city && req.driver.address?.state && req.driver.address?.pincode && req.driver.emergencyContact?.phone); await req.driver.save(); res.json({ success: true, driver: req.driver }); };
exports.upsertVehicle = async (req, res) => { const data = { ...req.body, driverId: req.driver._id }; if (data.registrationNumber) data.registrationNumber = data.registrationNumber.toUpperCase(); let vehicle = await Vehicle.findOne({ driverId: req.driver._id }); if (vehicle && vehicle.verificationStatus === "approved") return res.status(409).json({ success: false, message: "Approved vehicle details cannot be changed; contact support to start re-verification." }); try { vehicle = vehicle ? await Vehicle.findByIdAndUpdate(vehicle._id, data, { new: true, runValidators: true }) : await Vehicle.create(data); } catch (error) { return res.status(400).json({ success: false, message: error.code === 11000 ? "This registration number is already registered." : error.message }); } res.json({ success: true, vehicle }); };
exports.addDocument = async (req, res) => { const body = { ...req.body, driverId: req.driver._id }; if (!body.storageKey?.startsWith(`drivers/${req.driver._id}/`)) return res.status(400).json({ success: false, message: "Document must be stored in the driver's private storage path." }); if (expired(body.expiryDate)) return res.status(400).json({ success: false, message: "Expired documents cannot be submitted." }); const existing = await DriverDocument.findOne({ driverId: req.driver._id, documentType: body.documentType, documentNumber: body.documentNumber }); if (existing?.verificationStatus === "approved") return res.status(409).json({ success: false, message: "Approved documents cannot be modified; contact support to start re-verification." }); const document = existing ? await DriverDocument.findByIdAndUpdate(existing._id, { ...body, verificationStatus: "pending", rejectionReason: null, verifiedAt: null, verifiedBy: null }, { new: true, runValidators: true }) : await DriverDocument.create(body); res.status(existing ? 200 : 201).json({ success: true, document }); };
exports.submit = async (req, res) => { const [vehicle, documents] = await Promise.all([Vehicle.findOne({ driverId: req.driver._id }), DriverDocument.find({ driverId: req.driver._id })]); const missing = []; if (!req.driver.verification.profileCompleted) missing.push("Personal profile"); if (!req.driver.verification.phoneVerified) missing.push("Verified phone number"); if (!vehicle) missing.push("Vehicle details"); requiredTypes.forEach((type) => { const doc = documents.find((item) => item.documentType === type); if (!doc) missing.push(type); else if (expired(doc.expiryDate)) missing.push(`${type} (expired)`); }); if (missing.length) return res.status(400).json({ success: false, message: "Verification is incomplete.", incompleteRequirements: missing }); req.driver.verification.status = "under_review"; await req.driver.save(); await audit(req.driver._id, req.driver._id, "SUBMITTED", "Driver", req.driver._id); res.json({ success: true, message: "Verification submitted for review.", verification: req.driver.verification }); };
exports.pending = async (_req, res) => res.json({ success: true, drivers: await Driver.find({ "verification.status": { $in: ["under_review", "pending"] } }).select("-identity") });
exports.adminDetail = async (req, res) => { const [driver, vehicle, documents] = await Promise.all([Driver.findById(req.params.driverId).select("+identity"), Vehicle.findOne({ driverId: req.params.driverId }), DriverDocument.find({ driverId: req.params.driverId })]); if (!driver) return res.status(404).json({ success: false, message: "Driver not found." }); res.json({ success: true, driver, vehicle, documents }); };
exports.reviewDocument = async (req, res) => { const document = await DriverDocument.findOne({ _id: req.params.documentId, driverId: req.params.driverId }); if (!document) return res.status(404).json({ success: false, message: "Document not found." }); const approved = req.params.decision === "approve"; if (!approved && !req.body.reason?.trim()) return res.status(400).json({ success: false, message: "A rejection reason is required." }); document.verificationStatus = approved ? "approved" : "rejected"; document.rejectionReason = approved ? null : req.body.reason.trim(); document.verifiedBy = req.driver._id; document.verifiedAt = new Date(); await document.save(); await audit(document.driverId, req.driver._id, approved ? "DOCUMENT_APPROVED" : "DOCUMENT_REJECTED", "DriverDocument", document._id, document.rejectionReason); res.json({ success: true, document }); };
exports.reviewVehicle = async (req, res) => { const vehicle = await Vehicle.findOne({ _id: req.params.vehicleId, driverId: req.params.driverId }); if (!vehicle) return res.status(404).json({ success: false, message: "Vehicle not found." }); const approved = req.params.decision === "approve"; vehicle.verificationStatus = approved ? "approved" : "rejected"; await vehicle.save(); await audit(vehicle.driverId, req.driver._id, approved ? "VEHICLE_APPROVED" : "VEHICLE_REJECTED", "Vehicle", vehicle._id, req.body.reason); res.json({ success: true, vehicle }); };
exports.verifyPhone = async (req, res) => { const driver = await Driver.findById(req.params.driverId); if (!driver) return res.status(404).json({ success: false, message: "Driver not found." }); driver.verification.phoneVerified = true; await driver.save(); await audit(driver._id, req.driver._id, "PHONE_VERIFIED", "Driver", driver._id); res.json({ success: true, driver }); };
exports.finalDecision = async (req, res) => { const driver = await Driver.findById(req.params.driverId); if (!driver) return res.status(404).json({ success: false, message: "Driver not found." }); const approve = req.params.decision === "approve"; if (!approve) { if (!req.body.reason?.trim()) return res.status(400).json({ success: false, message: "A rejection reason is required." }); driver.status = "rejected"; driver.verification.status = "rejected"; driver.availability = "offline"; } else { const [vehicle, documents] = await Promise.all([Vehicle.findOne({ driverId: driver._id }), DriverDocument.find({ driverId: driver._id })]); const allDocumentsApproved = requiredTypes.every((type) => documents.some((doc) => doc.documentType === type && doc.verificationStatus === "approved" && !expired(doc.expiryDate))); if (!driver.verification.phoneVerified || !vehicle || vehicle.verificationStatus !== "approved" || !allDocumentsApproved) return res.status(400).json({ success: false, message: "Driver cannot be approved: phone, approved vehicle, or required approved documents are missing or expired." }); driver.verification.licenseVerified = documents.some((doc) => doc.documentType === "DRIVING_LICENSE" && doc.verificationStatus === "approved"); driver.verification.vehicleVerified = true; driver.verification.documentsVerified = allDocumentsApproved; driver.verification.status = "approved"; driver.status = "active"; } await driver.save(); await audit(driver._id, req.driver._id, approve ? "DRIVER_APPROVED" : "DRIVER_REJECTED", "Driver", driver._id, req.body.reason); res.json({ success: true, driver }); };
exports.suspend = async (req, res) => { const driver = await Driver.findByIdAndUpdate(req.params.driverId, { status: "suspended", availability: "offline", "verification.status": "suspended" }, { new: true }); if (!driver) return res.status(404).json({ success: false, message: "Driver not found." }); await audit(driver._id, req.driver._id, "DRIVER_SUSPENDED", "Driver", driver._id, req.body.reason); res.json({ success: true, driver }); };
exports.acceptRideGuard = (req, res) => { if (req.driver.role !== "driver" || req.driver.status !== "active" || req.driver.verification.status !== "approved") return res.status(403).json({ success: false, message: "Driver verification is not complete." }); res.json({ success: true, message: "Ride acceptance authorized." }); };
