"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { CarFront, LockKeyhole } from "lucide-react";
import { adminApi } from "@/lib/admin-api";
export default function LoginPage() {
  const router = useRouter(); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const data = new FormData(event.currentTarget); try { const result = await adminApi<{token:string}>("/login", { method: "POST", body: JSON.stringify({ email: data.get("email"), password: data.get("password") }) }); localStorage.setItem("moventra-admin-token", result.token); router.replace("/admin/dashboard"); } catch (e) { setError(e instanceof Error ? e.message : "Sign in failed."); } finally { setBusy(false); } }
  return <main className="grid min-h-screen bg-slate-50 lg:grid-cols-[1fr_1fr]"><section className="relative hidden flex-col justify-between overflow-hidden bg-slate-950 p-12 text-white lg:flex"><div className="absolute -right-40 -top-40 size-[500px] rounded-full border border-emerald-400/15"/><div className="absolute -right-20 -top-20 size-[340px] rounded-full border border-indigo-400/20"/><div className="relative flex items-center gap-3 text-lg font-bold"><span className="grid size-10 place-items-center rounded-xl bg-emerald-600"><CarFront/></span>Moventra</div><div className="relative max-w-lg"><div className="mb-4 text-sm font-semibold uppercase tracking-[.2em] text-emerald-400">Fleet operations</div><h1 className="text-4xl font-semibold leading-tight">Everything moving, in one place.</h1><p className="mt-4 text-slate-400">Manage drivers, vehicles, riders and trips with a clear view of your operation.</p></div><p className="relative text-xs text-slate-500">Secure administrator access</p></section><section className="flex items-center justify-center p-6"><form onSubmit={submit} className="w-full max-w-sm"><div className="mb-8 lg:hidden"><span className="inline-flex items-center gap-2 font-bold"><CarFront className="text-emerald-700"/>Moventra Admin</span></div><div className="mb-2 grid size-12 place-items-center rounded-2xl bg-emerald-100 text-emerald-800"><LockKeyhole/></div><h2 className="mt-5 text-2xl font-bold text-slate-900">Administrator sign in</h2><p className="mt-2 text-sm text-slate-500">Use your existing administrator account.</p><label className="mt-7 block text-sm font-medium">Email address<input name="email" type="email" autoComplete="username" required className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-3.5 py-3 outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100" placeholder="you@company.com"/></label><label className="mt-4 block text-sm font-medium">Password<input name="password" type="password" autoComplete="current-password" required className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-3.5 py-3 outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100" placeholder="Enter your password"/></label>{error && <p role="alert" className="mt-4 rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}<button disabled={busy} className="mt-6 w-full rounded-xl bg-emerald-700 px-4 py-3 font-semibold text-white hover:bg-emerald-800 disabled:opacity-60">{busy?"Signing in…":"Sign in"}</button><p className="mt-5 text-xs leading-5 text-slate-400">Access is granted only to accounts with the administrator role.</p></form></section></main>;
}
