"use client";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, Check, FileText, RefreshCw, X } from "lucide-react";
import { adminApi } from "@/lib/admin-api";
type Data={driver:any;vehicle:any;documents:any[]};
const docLabels:Record<string,string>={DRIVING_LICENSE:"Driving license",IDENTITY_PROOF:"Identity proof",VEHICLE_RC:"Vehicle RC",VEHICLE_INSURANCE:"Insurance",POLLUTION_CERTIFICATE:"Pollution certificate",VEHICLE_PERMIT:"Vehicle permit",FITNESS_CERTIFICATE:"Fitness certificate"};
export default function DriverDetail(){const {driverId}=useParams<{driverId:string}>();const router=useRouter();const [data,setData]=useState<Data|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError("");try{setData(await adminApi<Data>(`/drivers/${driverId}`))}catch(e){setError(e instanceof Error?e.message:"Unable to load driver.")}finally{setLoading(false)}},[driverId]);useEffect(()=>{load()},[load]);
 async function action(path:string,reason?:string){setBusy(true);try{await adminApi(path,{method:"PATCH",body:JSON.stringify(reason?{reason}:{})});await load()}catch(e){setError(e instanceof Error?e.message:"Action failed.")}finally{setBusy(false)}}
 if(loading)return <div className="animate-pulse rounded-2xl bg-white p-8 text-slate-400">Loading driver details…</div>;if(!data)return <div className="rounded-2xl bg-white p-8 text-center text-slate-600">{error||"Driver not found."}<button className="ml-3 text-emerald-700" onClick={()=>router.push("/admin/drivers")}>Back to drivers</button></div>;
 const {driver,vehicle,documents}=data;const addr=driver.address;return <div><Link href="/admin/drivers" className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-emerald-700"><ArrowLeft size={16}/>All drivers</Link><div className="mt-5 flex flex-wrap items-start justify-between gap-4"><div><div className="text-sm text-slate-500">Driver profile</div><h1 className="mt-1 text-2xl font-bold text-slate-900">{driver.name}</h1><p className="mt-1 text-sm text-slate-500">Registered {new Date(driver.createdAt).toLocaleDateString()} · {driver.email}</p></div><div className="flex flex-wrap gap-2"><button disabled={busy} onClick={()=>action(`/drivers/${driverId}/approve`)} className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><Check size={16}/>Approve driver</button><button disabled={busy} onClick={()=>{const reason=window.prompt("Provide a reason for rejection");if(reason?.trim())action(`/drivers/${driverId}/reject`,reason)}} className="inline-flex items-center gap-2 rounded-xl border border-red-200 bg-white px-4 py-2.5 text-sm font-semibold text-red-700 disabled:opacity-50"><X size={16}/>Reject</button><button disabled={busy} onClick={()=>{const reason=window.prompt("Reason for suspension (optional)")||"";action(`/drivers/${driverId}/suspend`,reason)}} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-medium text-slate-600">Suspend</button></div></div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
 <div className="mt-6 grid gap-5 lg:grid-cols-2"><Panel title="Personal information"><Info label="Full name" value={driver.name}/><Info label="Email" value={driver.email}/><Info label="Phone" value={driver.phone}/><Info label="Date of birth" value={driver.dateOfBirth?new Date(driver.dateOfBirth).toLocaleDateString():"—"}/><Info label="Address" value={[addr?.line1,addr?.city,addr?.state,addr?.pincode].filter(Boolean).join(", ")||"—"}/><Info label="Registration date" value={new Date(driver.createdAt).toLocaleString()}/></Panel><Panel title="Driver status"><Info label="Account status" value={driver.status}/><Info label="Verification" value={driver.verification?.status}/><Info label="Availability" value={driver.availability}/><Info label="Phone verified" value={driver.verification?.phoneVerified?"Yes":"No"}/>{!driver.verification?.phoneVerified&&<button onClick={()=>action(`/drivers/${driverId}/phone/verify`)} className="mt-2 rounded-lg bg-indigo-50 px-3 py-2 text-xs font-semibold text-indigo-700">Mark phone verified</button>}</Panel>
 <Panel title="Vehicle"><div className="grid grid-cols-2 gap-x-5">{vehicle?<><Info label="Vehicle type" value={vehicle.vehicleType}/><Info label="Brand" value={vehicle.brand}/><Info label="Model" value={vehicle.model}/><Info label="Registration" value={vehicle.registrationNumber}/><Info label="Color" value={vehicle.color}/><Info label="Year" value={vehicle.manufacturingYear}/><Info label="Seats" value={vehicle.seats}/><Info label="Fuel type" value={vehicle.fuelType}/><Info label="Verification" value={vehicle.verificationStatus}/></>:<p className="py-4 text-sm text-slate-500">No vehicle record available.</p>}</div>{vehicle&&vehicle.verificationStatus!=="approved"&&<div className="mt-4 flex gap-2"><button onClick={()=>action(`/drivers/${driverId}/vehicles/${vehicle._id}/approve`)} className="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-700">Approve vehicle</button><button onClick={()=>{const r=window.prompt("Reason for rejecting this vehicle");if(r?.trim())action(`/drivers/${driverId}/vehicles/${vehicle._id}/reject`,r)}} className="rounded-lg bg-red-50 px-3 py-2 text-xs font-semibold text-red-700">Reject vehicle</button></div>}</Panel>
 <Panel title="Verification documents"><div className="space-y-3">{documents.length?documents.map((doc:any)=><div key={doc._id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-100 p-3"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-indigo-50 text-indigo-700"><FileText size={17}/></span><div><div className="text-sm font-medium">{docLabels[doc.documentType]||doc.documentType}</div><div className="text-xs text-slate-500">Uploaded {new Date(doc.createdAt).toLocaleDateString()}</div></div></div><div className="flex items-center gap-2"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs capitalize text-slate-600">{doc.verificationStatus}</span>{doc.verificationStatus!=="approved"&&<><button aria-label="Approve document" onClick={()=>action(`/drivers/${driverId}/documents/${doc._id}/approve`)} className="rounded-lg p-2 text-emerald-700 hover:bg-emerald-50"><Check size={16}/></button><button aria-label="Reject document" onClick={()=>{const r=window.prompt("Reason for rejecting this document");if(r?.trim())action(`/drivers/${driverId}/documents/${doc._id}/reject`,r)}} className="rounded-lg p-2 text-red-700 hover:bg-red-50"><X size={16}/></button></>}</div></div>):<p className="py-4 text-sm text-slate-500">No verification documents submitted.</p>}</div><p className="mt-4 text-xs text-slate-400">Document previews will be available when the GridFS document endpoint is integrated.</p></Panel></div><button onClick={load} className="mt-5 inline-flex items-center gap-2 text-sm text-slate-500"><RefreshCw size={14}/>Refresh profile</button></div>
}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 font-semibold text-slate-900">{title}</h2>{children}</section>}function Info({label,value}:{label:string;value:any}){return <div className="mb-3"><div className="text-xs text-slate-500">{label}</div><div className="mt-1 text-sm font-medium capitalize text-slate-800">{value||"—"}</div></div>}
